### ISSUE TITLE
Underscore 升级到 1.7 之后，Loading 组件不能正常工作

### ISSUE THREAD

**Issue by cssmagic** [CMUI/CMUI#14]
主要原因是 `_.union()` API 的行为有变化。以下代码在 1.6- 和 1.7 中的结果不同：

```js
_.union([1], 2)
```

必须写成以下方式才能得到预期结果：

```js
_.union([1], [2])
```

除此以外，Underscore 1.7  的很多 API 行为都有变化。

API 变得更严格我很理解并赞同，但 API 行为变化之后大版本号并没有变，感觉很不爽，险些中招啊。Lo-dash 嘲讽 Underscore 不支持 semver 果然是有道理的。

**Comment by zEmily** [comment]
确实好坑。。。。
