### ISSUE TITLE
[BX Theme] `article > main` 布局似乎考虑过多了，反而限制了实际开发的便利性

### ISSUE THREAD

**Issue by cssmagic** [CMUI/CMUI#19]
`article > main` 默认设置了左右内边距，而如果其内容区块需要显示为全宽时，则需要调用 `full-width-block()` 这个 mixin——它的原理是通过水平方向上负外边距来突破 main 的内容区的。而这些内容区块自己可能也需要设置水平内边距，于是整个过程就变得相当折腾了。

为 `article > main` 指定默认的左右内边距是为了快速实现简单页面——直接写内容即可，内容不会贴到边。但实际开发中这种场景其实非常有限，几乎所有的页面都是经过充分美化的。

**Comment by OTTooo** [comment]
你好这篇文章我有一个疑问，https://github.com/rccoder/blog/issues/6
对负margin应用在float元素上有点不太明白，想不明白为什么left元素设置margin-left：-100%，可以浮动到上一行，感觉它应该是偏移出屏幕？

**Comment by cssmagic** [comment]
@OTTooo 
原文作者已经回复你了。话说你怎么会跑到这里来问这个问题？ 😂

**Comment by cssmagic** [comment]
v2.0 已经做相应修改。
