### ISSUE TITLE
使用 clean-css 压缩 CSS 会导致 Firefox 下样式异常

### ISSUE THREAD

**Issue by cssmagic** [CMUI/CMUI#7]
### 问题

目前在使用 CSS 代码压缩工具是 [clean-css](https://github.com/GoalSmashers/clean-css)，使用方便，压缩率高。

但存在一个问题，它默认会把所有 `rgba(*,*,*,0)` 转换成 `transparent`。而（我估计）在 Firefox 内核中 `transparent` 是直接绑定了 `rgba(0,0,0,0)` 的，那么在发生颜色插值运算的场景下（transition、gradient、不同边框色的斜边交界等），Firefox 在计算中间色调时会出现问题，观感上表现为半透明的黑色乱入。

对 CMUI 的样式来说，这个问题会影响到按钮和列表等元素的渐变背景等。
### 解决方案

在使用 clean-css 压缩 CSS 代码时，增加 `-c *` 参数，强制关闭这种透明色转换行为。

``` bash
$ cleancss -o cmui.min.css --s1 -d -c * cmui.css
```

**Comment by cssmagic** [comment]
貌似 `-c *` 是 clean-css 的默认配置……

Clean-css 的文档写得真的不怎么样，各配置项的含义表述不清，各配置项的功能看起来也有相互重叠的地方，遇到问题只能读源码。

**Comment by hax** [comment]
算是蛮正交了，但是css本身各项特性并不是正交的，所以……

**Comment by hax** [comment]
这个问题是 rgba(*, *, *, 0) 在参与 transition 时和 transparent 的行为是不一致的？

**Comment by cssmagic** [comment]
> 这个问题是 rgba(*, *, *, 0) 在参与 transition 时和 transparent 的行为是不一致的？

没读过规范，但以我的理解，应该是不一致的。RGBA 中的四个值应该是单独参与过渡计算的。

因此，以我的理解：

* 当 `rgba(1,1,1,255)` 与 `transparent` 之间做过渡时，`transparent` 应该被解读为 `rgba(1,1,1,0)`
* 当 `rgba(2,2,2,255)` 与 `transparent` 之间做过渡时，`transparent` 应该被解读为 `rgba(2,2,2,0)`

只有这样，结果才是符合预期的。

**Comment by cssmagic** [comment]
> 但是看上去cleancss本身有处理这个问题啊：https://github.com/jakubpawlowicz/clean-css/blob/master/test/selectors/optimizers/simple-test.js#L209-L212
> 
> 看了下是去年10月份加的，估计你写的时候是有问题。

那 clean-css 可能已经针对 Firefox 的问题修正过了。

**Comment by hax** [comment]
貌似现在的firefox就是按照你说的方式的，难道是fix了？

**Comment by hax** [comment]
哦，我知道了，是理解错误。实际的颜色分量的插值算法是对“颜色分量 * alpha分量”的结果进行插值。所以其实始终是按 rgba(0, 0, 0, 0) 计算的。或者说此插值算法确保了按照 rgba(*, *, *, 0) 计算和 rgba(0, 0, 0, 0) 计算的结果是一致的（因为任何分量 * 0的结果都是0）。

**Comment by hax** [comment]
spec在此：http://dev.w3.org/csswg/css-transitions/#animtype-color

**Comment by cssmagic** [comment]
我顺道查了 `transparent` 在 CSS3 spec 中的定义：
http://dev.w3.org/csswg/css-color-3/#transparent

> `transparent`
> Fully transparent. This keyword can be considered a shorthand for transparent black, `rgba(0,0,0,0)`, which is its computed value.

这样看来，结合你列的 spec 中 transition 的算法，Firefox 的行为居然是符合规范的？（也就是说，我对 `transparent` 的理解是错误的？）

在最终下结论之前，我会再找你面对面确认一下。

**Comment by hax** [comment]
测试代码 http://jsfiddle.net/cr1av2eg/3/

**Comment by cssmagic** [comment]
> http://dev.w3.org/csswg/css-transitions/#animtype-color

> color: interpolated via red, green, blue and alpha components (treating each as a number, see below). The interpolation is done between premultiplied colors (that is, colors for which the red, green, and blue components specified have been multiplied by the alpha).

我搞错了，我对颜色的插值算法的理解是不正确的！规范要求以 premultiplied 算法来进行插值计算，如 @hax 所说，此时 `rgba(0,0,0,0)` 的行为与任何最终效果为透明的 RGBA 颜色无异。因此 Firefox 早期版本的行为是不正确的，但后来已修正。

BTW，《CSS Secrets》在 “滚动提示” 一节中也提醒了这种行为不一致的情况。

**Comment by hax** [comment]
所以这个case对应的commit应该reverse掉？

**Comment by cssmagic** [comment]
那倒不需要。相关 commit 只是用来避免源码中的 `rgba(*,*,*,0)` 在压缩过程中被替换为 `transparent`。替换前和替换后的代码其实是等效的（但后者更有益于 Gzip），即 clean-css 的这种行为其实是正确的。

**Comment by hax** [comment]
我就是意思恢复到clean-css的默认行为是不是更好。

**Comment by cssmagic** [comment]
因为是旧版（`v0` 分支）的代码，而且不是 bug，“兼容性” 也更好，就不打算改了。  :sweat_smile:

**Comment by yisibl** [comment]
哈哈 Safari 至今还没修复这个 transparent 的 bug 

![image](https://cloud.githubusercontent.com/assets/2784308/25041525/3362162a-2143-11e7-9b37-4f7f2cf862f0.png)

**Comment by cssmagic** [comment]
唉……
